[dotfiles]
"~/.config/mise/config.toml" = { mode = "track" }
"~/.zshrc" = { mode = "track" }
[bootstrap.services.mise-history]
builtin = "history-watch"

[tools]
gh = "latest"

[bootstrap.packages]
"brew-cask:ghostty" = "latest"
"brew-cask:chatgpt" = "latest"
